asset: release/metax.tar.gz
tap: meta-lang/homebrew-metax/app.rb
template: |
  class Metax < Formula
    desc     "$REPO_DESCRIPTION"
    homepage "$REPO_WEBSITE"
    version  "$STABLE_VERSION"
    url      "$STABLE_ASSET_URL"
    sha256   "$STABLE_ASSET_SHA256"

    def install
      prefix.install "metax"
    end
  end